// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

// RWTexture2D<int4> Result;

int granularityMethod;
float distanceThreshold;
int image_width;
int image_height;
Texture2D<int4> backgroundRenderTexture;
Texture2D<int4> labelRenderTexture;
RWTexture2D<int4> Result; // this has to be 2D
// SamplerState _LinearClamp;

float2 pixel_to_coord(int2 pixel, int image_width, int image_height){
    // Convert pixel position to spherical coordinates
    float lon = (pixel[0] / image_width) * 360 - 180;
    float lat = 90 - (pixel[1] / image_height) * 180;
    float2 result = float2(lon, lat);
    return result;
}

float great_circle_distance(int2 target_pixel, int2 source_pixel, int image_width, int image_height){
    // Assuming the image represents a full 360 degree view of the sphere
    // Convert pixel coordinates to longitude and latitude
    float2 lon1lat1 = pixel_to_coord(target_pixel, image_width, image_height);
    float lon1 = lon1lat1[0];
    float lat1 = lon1lat1[1];

    float2 lon2lat2 = pixel_to_coord(source_pixel, image_width, image_height);
    float lon2 = lon2lat2[0];
    float lat2 = lon2lat2[1];
    
    // Convert degrees to radians
    // lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])
    lon1 = radians(lon1);
    lat1 = radians(lat1);
    lon2 = radians(lon2);
    lat2 = radians(lat2);
    
    // Haversine formula
    float dlon = lon2 - lon1;
    float dlat = lat2 - lat1;
    float a = pow(sin(dlat/2), 2) + cos(lat1) * cos(lat2) * pow(sin(dlon/2), 2);
    float c = 2 * asin(sqrt(a));
    
    // Radius of the image in pixels (mean radius)
    float R = image_width/(2*radians(180));
    float distance = R * c;
    
    return distance;
}

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // float3 resolution = float3(2048, 2048, 2048);  //cubemap resolution
    // float3 pixel = float3(id.x, id.y, id.z);  //pixel coordinates
    // float3 uv = pixel/resolution;  //normalized uv coordinates
    // half4 labelCubemapPixelVal = labelRenderTexture.SampleLevel(_LinearClamp,uv,0);
    // Mask the background cubemap according to granularity method
    if (granularityMethod == 0 || granularityMethod == 1){
        if (labelRenderTexture[id.xy].x > 200 && labelRenderTexture[id.xy].y > 200 && labelRenderTexture[id.xy].z > 200){ // is a label
            Result[id.xy] = backgroundRenderTexture[id.xy];
        }
        else{
            Result[id.xy] = int4(0, 0, 0, 0);
        }

    }

    else if (granularityMethod == 2){
        float distance = 0;
        if (distance <= distanceThreshold){
            // int distanceAsInt = int(distance*255);
            Result[id.xy] = backgroundRenderTexture[id.xy];
        }
        else{
            Result[id.xy] = int4(0, 0, 0, 0);
        }
    }
}
